name: bibliotek-compose

services:
  biblio-mysql:
    image: mysql:8.0.44-debian #adapter sur windows
    container_name: bibliotek-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

    volumes:
      - db_data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/setup.sql

    networks:
      - biblio


  biblio-boot:

    image: ajc/bibliotek:boot
    container_name: bibliotek-boot

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bibliotek-mysql/library
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      biblio-mysql:
        condition: service_healthy

    ports:
      - "3307:3306" 

    networks:
      - biblio


  biblio-angular:
    image: ajc/bibliotek:angular
    container_name: bibliotek-angular

    ports:
      - 81:81

    depends_on:
      - biblio-boot

    networks:
      - biblio

volumes:
  db_data:
    name: biblio-db-data

networks:
  biblio:
    name: biblio
